; This is a settings export file for the WordPress SEO plugin by Yoast.com - http://yoast.com/wordpress/seo/

[wpseo]
ignore_blog_public_warning = 
ignore_page_comments = 
ignore_permalink = 
ms_defaults_set = 
usemetakeywords = "on"
googleverify = "<meta name="google-site-verification" content="sIQYRtUBvIVduI016Ab6o8D-PPEKzF1iUB3salgBLm0" />"
yahooverify = "<meta name="y_key" content="84503749a58fbd4e" />"
msverify = "<meta name="msvalidate.01" content="1CA9081E02637F1E292A81FC1AE0DE0C" />"
version = "1.0.2.3"

[wpseo_indexation]
ignore_blog_public_warning = 
ignore_page_comments = 
ignore_permalink = 
ms_defaults_set = 
fb_pageid = 
fb_adminid = 
fb_appid = 
search = "on"
logininput = "on"
admin = "on"
noindexauthor = "on"
noindexdate = "on"
noindextag = "on"
nofollowmeta = "on"
nofollowcommentlinks = "on"
replacemetawidget = "on"
disableauthor = "on"
hidersdlink = "on"
hidewlwmanifest = "on"

[wpseo_permalinks]

[wpseo_titles]
ignore_blog_public_warning = 
ignore_page_comments = 
ignore_permalink = 
ms_defaults_set = 
title-home = "%%sitename%% - %%sitedesc%%"
metadesc-home = 
metakey-home = 
title-post = "%%title%% - %%sitename%%"
metadesc-post = "%%excerpt%%"
metakey-post = "%%focuskw%%, %%tag%%"
title-page = "%%title%% - %%sitename%%"
metadesc-page = "%%excerpt%%"
metakey-page = "%%focuskw%%, %%tag%%"
title-attachment = "%%title%% - %%sitename%%"
metadesc-attachment = "%%caption%%"
metakey-attachment = "%%focuskw%%, %%tag%%"
title-category = "%%term_title%% - %%sitename%%"
metadesc-category = "%%category_description%%"
metakey-category = "%%term_title%%"
title-post_tag = "%%term_title%% - %%sitename%%"
metadesc-post_tag = "%%tag_description%%"
metakey-post_tag = "%%term_title%%"
title-author = "%%name%% - %%sitename%%"
metadesc-author = "Author Profile of %%name%% at %%sitename%%"
metakey-author = "%%name%%, %%sitename%%"
title-archive = 
metadesc-archive = 
title-search = "%%searchphrase%% - %%sitename%%"
title-404 = "Page Not Found - %%sitename%%"

[wpseo_rss]

[wpseo_internallinks]
ignore_blog_public_warning = 
ignore_page_comments = 
ignore_permalink = 
ms_defaults_set = 
breadcrumbs-enable = "on"
breadcrumbs-sep = "&raquo;"
breadcrumbs-home = "Gautam's Blog"
breadcrumbs-prefix = "You are here:"
breadcrumbs-archiveprefix = "Archives for"
breadcrumbs-searchprefix = "You searched for:"
breadcrumbs-404crumb = "Page not found..."
post_types-post-maintax = "category"
breadcrumbs-boldlast = "on"
breadcrumbs-trytheme = "on"

[wpseo_xml]
ignore_blog_public_warning = 
ignore_page_comments = 
ignore_permalink = 
ms_defaults_set = 
enablexmlsitemap = "on"
xml_include_images = "on"
xml_ping_google = "on"
xml_ping_bing = "on"
xml_ping_yahoo = "on"
xml_ping_ask = "on"
